name: Sync with upstream repository

on:
  schedule:
    - cron: '10 * * * *'  # 每天北京时间 00:00 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/lxw15337674/weibo-trending-hot-history.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          # 尝试直接合并上游分支到主分支，允许合并无关联历史
          git merge upstream/master --no-commit --no-ff --allow-unrelated-histories
          if [ $? -ne 0 ]; then
            # 处理合并冲突，保留本地文件
            git checkout --ours sync-upstream.yml
            git add sync-upstream.yml
            git commit -m "Merge upstream changes, keep sync-upstream.yml"
          else
            git commit -m "Merge upstream changes"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
