name: Sync with upstream repository

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/lxw15337674/weibo-trending-hot-history.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          # 尝试合并并自动处理冲突
          if git merge upstream/master --no-commit --no-ff --allow-unrelated-histories -X theirs; then
            git commit -m "Merge upstream changes"
          else
            # 显式处理冲突（此处使用-X theirs已处理大部分情况，保留此逻辑以防万一）
            git diff --name-only --diff-filter=U | while read file; do
              # 特殊处理sync-upstream.yml保留本地版本
              if [[ "$file" == "sync-upstream.yml" ]]; then
                git checkout --ours -- "$file"
              fi
              git add "$file"
            done
            git commit -m "Merge upstream changes: Resolve conflicts by preferring upstream"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
